### ISSUE TITLE
Include reaction_added and reaction_removed support on Real Time API

### ISSUE THREAD

**Issue by ajmarquez** [dblock/slack-ruby-client#14]
The RealTime API has many methods, two of which are still not supported by the repository which are:

- reaction_added: A team member has added an emoji reaction to an item
- reaction_removed: A team member removed an emoji reaction

**Comment by dblock** [comment]
Please feel free to PR!

**Comment by dblock** [comment]
Was done in https://github.com/dblock/slack-ruby-client/commit/a19f4df0841cebdbced45724d919f3d9c8b8f467.

**Comment by MarioRuiz** [comment]
@dblock reaction_added and reaction_removed was not added yet on that MR and it seems it is still not included.

**Comment by dblock** [comment]
> @dblock reaction_added and reaction_removed was not added yet on that MR and it seems it is still not included.

Want to go through https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#update-slack-web-api? I would also start by confirming that slack-api-ref is up-to-date, it hasn't seen any updates oddly for a while, it's probably broken. See https://github.com/slack-ruby/slack-api-ref/issues/45 too.
