### ISSUE TITLE
Protection against flood loop

### ISSUE THREAD

**Issue by Nakilon** [dblock/slack-ruby-client#17]
You may be interested in:
1) respecting https://api.slack.com/docs/rate-limits
2) ignoring message from itself
These things together can loop and flood the server with messages.

I'm lazy to write tests so I'll just leave my monkey-patch for gem v0.3.0. Instead of rewriting `dispatch` one probably could wrap each "message" callback in one for check but it would be harder with dynamic adding callbacks.
```
Slack::RealTime::Api::Message.module_eval do
  alias :message_old :message
  def message *args
    message_old *args
    sleep 1
  end
end

Slack::RealTime::Client.class_eval do
  alias :old_initialize :initialize
  def initialize *args
    old_initialize *args
    @callbacks = Hash.new{ |h, k| h[k] = [] }
  end
  protected
  def dispatch event
    return false unless event.data
    data = JSON.parse event.data
    return false unless type = data["type"]
    return false unless callbacks = @callbacks[type]
    callbacks.each do |c|
      c.call data unless type == "message" && self.self["id"] == data["user"]
    end.empty? ^ true
  end
end
```

**Comment by dblock** [comment]
Explicitly ignoring messages from self is definitely something that should be on by default. Would love a proper PR for this.

**Comment by dblock** [comment]
I don't think this belongs in slack-ruby-client because a message is a message and downstream clients may want to notice that their own message was delivered. However I've implemented this in https://github.com/dblock/slack-ruby-bot/commit/3a54456d5893c63c98a1595d4404cf00af1c1a4e for slack-ruby-bot as a feature. Closing this here.
