### ISSUE TITLE
how to set the proxy so I can use Runscope?

### ISSUE THREAD

**Issue by timfong888** [dblock/slack-ruby-client#19]
Hi, I see in the docs support for proxy:

proxy	Optional HTTP proxy.

I want to pass a different URL so that i can use the Runscope gateway URL to monitor how it works with Slack....is there a doc that explains how I would do that?

**Comment by dblock** [comment]
Specifying the proxy is like so: https://github.com/dblock/slack-ruby-client/blob/fcdc4b1c90df51ce14cf85480e0de47f9a2bc1a9/spec/slack/web/client_spec.rb#L83

```ruby
Slack::Web::Client.configure do |config|
    config.proxy = 'http://localhost:8080'
end
```

If the doc is lacking please contribute! LMK if this worked.

**Comment by timfong888** [comment]
cool, how can I best contribute, a PR to your wiki?  I started looking into the docs and playing with the client, and now not sure whether it should be endpoint I change or proxy...

Runscope gives a revised end-point and they proxy the traffic....be glad to contribute to docs, love what you have done!

**Comment by timfong888** [comment]
ah, it was endpoint not proxy, works like a charm now!  thanks.

**Comment by dblock** [comment]
PR always, into the README. So you just set the endpoint? If the doc can be more clear, just make a pull request with whatever it is that would have helped you not need to ask this question.  I'll close this.
