### ISSUE TITLE
Inherit Slack::Web::Api::Error from Faraday::ClientError

### ISSUE THREAD

**Issue by technicalpickles** [dblock/slack-ruby-client#22]
Currently, it inherits from [Faraday::Error](https://github.com/dblock/slack-ruby-client/blob/master/lib/slack/web/api/error.rb#L4). The problem with this is that this doesn't have access to the response that caused the error. If this was `[Faraday::ClientError](https://github.com/lostisland/faraday/blob/master/lib/faraday/error.rb#L5)` instead, you can catch and access the response object.

**Comment by dblock** [comment]
Makes sense, I'd take a PR for that.

**Comment by dblock** [comment]
Turned out a little too complicated to change the inheritance, `ClientError` tries to do too many smart things. Ended up exposing `response` as is, see https://github.com/dblock/slack-ruby-client/commit/636f6c1d9b2f926b64a91a16190ca09fdc19340e.
