### ISSUE TITLE
Partition this gem?

### ISSUE THREAD

**Issue by dominicsayers** [dblock/slack-ruby-client#23]
Have you considered partitioning this gem into (maybe) `slack_web_client` and `slack_real_time_client`?

For my own project I have no need of the real time client, and it doesn't look like the web client depends on it at all. This would reduce the amount of code in my project and remove the dependency on `faye-websocket` too.

The real time client gem could then be built with the web client as a dependency.

**Comment by dblock** [comment]
I am not against it, but that wasn't built separately from the start, so here we are.

I think Slack will continue introducing a lot of other API things and it's easier to have a single client deal with everything. Regarding dependencies we want the EM dependency to be removed anyway unless you use EventMachine, see https://github.com/dblock/slack-ruby-client/issues/5, so it will achieve that part for you.

**Comment by dblock** [comment]
Btw, @dominicsayers you could help by completing part of #5 which extracts and abstracts the EM code without adding the Celluloid version. That alone would be a valuable addition and would solve your request on removing the `faye-websocket` dependency.

**Comment by dblock** [comment]
Celluloid support has been merged on HEAD, which removes the hard dependency on eventmachine and faye-websocket, @dominicsayers please give it a try.

**Comment by dominicsayers** [comment]
Will do, thanks @dblock

**Comment by dominicsayers** [comment]
Working fine for me. About to release my project to staging without `faye-websocket`

**Comment by dblock** [comment]
I will close this as "won't fix" since I don't like the idea of splitting the gem. Thanks for your suggestion!

**Comment by pusewicz** [comment]
For people who do not use the realtime functionality, many pulled in gems are not necessary and they are a liability and/or maintenance cost. The `websocket-driver` is a good candidate to get rid of.

**Comment by dblock** [comment]
We discussed this later in https://github.com/slack-ruby/slack-ruby-client/issues/229 for web/rtm api split and talked about splitting the command line in https://github.com/slack-ruby/slack-ruby-client/issues/128. I think the later makes immediate sense, @pusewicz feel free to do the work and we can delete the `gli` dependency from here.
