### ISSUE TITLE
Where to post the client.start! code?

### ISSUE THREAD

**Issue by LucasCioffi** [dblock/slack-ruby-client#25]
[This example](https://github.com/dblock/slack-ruby-client/blob/master/examples/hi_real_time_and_web/hi.rb) works great in the rails console.

1. Where would you put it in the app (in a controller, in a config file, etc)?

2. If the app is using the Puma web server, does the WebSocket that this code creates consume a worker or does it consume a thread?

Thanks for any advice!

**Comment by dblock** [comment]
You might want to check out https://github.com/dblock/slack-ruby-bot, a slightly higher level version that does a lot more heavy lifting for you. It also describes [how to write a production bot](https://github.com/dblock/slack-ruby-bot/blob/master/TUTORIAL.md), which is probably what you're looking for.

Other than that, a thread works, but you could also use `EM.run` around your web server which could load and launch the client via an explicit `require`.

**Comment by LucasCioffi** [comment]
Thank you for pointing me in the right direction, @dblock.
