### ISSUE TITLE
Introduce non blocking mode.

### ISSUE THREAD

**Issue by mikz** [dblock/slack-ruby-client#28]
I want to mix Slack client in the same process as a web server.

That means Slack client can't have blocking loop, but rather just run in the background.

See 1872a12 how it looks. I use it in https://github.com/mikz/october/pull/29 to have a bot with also listens for webhooks.

**Comment by dblock** [comment]
I had the same problem with EventMachine in https://github.com/dblock/slack-bot-server, and extracted myself https://github.com/dblock/slack-ruby-client/blob/master/lib/slack/real_time/concurrency/faye.rb, which just doesn't have any EventMachine code. Would that be cleaner with a similar implementation just with a different socket class that works with Celluloid?

**Comment by mikz** [comment]
@dblock faye-websocket still depends on eventmachine - https://github.com/faye/faye-websocket-ruby/blob/7e8c8fa75cbd0e5694092ea4227988846729c2e4/lib/faye/websocket/client.rb#L46-L48

But, I get your point and it might be worth having AsyncCelluloid which would have non blocking `#run` method and `Celluloid` which would build on it and just wait for that actor to finish, thus blocking.

Wdyt?

**Comment by dblock** [comment]
Oh I didn't realize that about faye-websocket. I guess that explains some issues I've been having trying to decouple things :)

I think what you suggest about Celluloid makes total sense. This is all about whether concurrency is managed inside slack-ruby-client (easy) or not (when you know what you're doing :).

**Comment by dblock** [comment]
I think similarly to `Faye::Socket` you probably want `WebSocket::Driver::Socket`, that has nothing to do with Celluloid.

**Comment by mikz** [comment]
@dblock I don't get the point about `Faye::Socket` and `WebSocket::Driver::Socket`.

I could not find any `WebSocket::Driver::Socket` in the websocket-driver. The socket passed to `WebSocket::Driver.client` is TCPSocket from Celluloid::IO.
Where in faye-websocket it passes [self (Faye::WebSocket::Client)](https://github.com/faye/faye-websocket-ruby/blob/7e8c8fa75cbd0e5694092ea4227988846729c2e4/lib/faye/websocket/client.rb#L17).


But when digging through the faye source, I found that they can start eventmachine reactor in different thread https://github.com/faye/faye-websocket-ruby/blob/d8b5a2c5532b1ad259ac17e0fe809ae37d793c3e/lib/faye/websocket.rb#L35-L38
That could be also used to async faye implementation, which does not block the main thread.

**Comment by dblock** [comment]
I think I am more confused about the async stuff than you :) Make the changes that you think fit, lets talk it over code in pull requests?

**Comment by dblock** [comment]
Closed via #29.
