### ISSUE TITLE
Are slash commands supported?

### ISSUE THREAD

**Issue by barmstrong** [dblock/slack-ruby-client#35]
Didn't see anywhere in the docs if slash commands like /giphy are supported?

**Comment by barmstrong** [comment]
It looks like they aren't. Although you can separately register a / command and point it to the sinatra web.rb routes to integrate something there. Thanks!

**Comment by dblock** [comment]
Right. Could use some documentation update about this for [slack-ruby-bot](github.com/dblock/slack-ruby-bot), but this project is just a client.
