### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by barmstrong** [dblock/slack-ruby-client#36]
It seems like if you include `attachments` via the real time API they don't show up, but they work if you change `client.web_client.chat_postMessage(...)`. Bug? Thanks!

**Comment by dblock** [comment]
Not a bug. This is documented in the Slack API, https://api.slack.com/rtm.

<img width="674" alt="screenshot 2015-12-04 00 00 33" src="https://cloud.githubusercontent.com/assets/542335/11582230/15180ad2-9a1a-11e5-9d5d-560560fb9d76.png">
