### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by callumacrae** [dblock/slack-ruby-client#37]
https://github.com/dblock/slack-ruby-client/blob/master/lib/slack/web/api/endpoints/oauth.rb

How do I actually use this? There is no documentation that I can find. I have my application registered as such, and so don't want to get an API key as well.

**Comment by dblock** [comment]
See https://api.slack.com/methods/oauth.access. 

_This method allows you to exchange a temporary OAuth code for an API access token. This is used as part of the [OAuth authentication flow](https://api.slack.com/docs/oauth)_.

**Comment by callumacrae** [comment]
It needs to hit `https://slack.com/oauth/authorize` first, though, to get the `code` attribute. Then, it needs to modify the config to set the returned key: and I'm not sure how to do that.

**Comment by callumacrae** [comment]
Relevant, this happened today: https://medium.com/slack-developer-blog/launch-platform-114754258b91#.jg6wupmid

**Comment by dblock** [comment]
I opened https://github.com/dblock/slack-bot-server/issues/1, I think a straightforward work-item is to implement OAuth there as a demo.

**Comment by dblock** [comment]
@callumacrae This was easy, updated in https://github.com/dblock/slack-bot-server/commit/a6266cff62d39e9674adb0e49d1114a5f082c3bf. Also updated http://code.dblock.org/2015/11/14/writing-a-slack-bot-service-for-multiple-teams.html with details about how to do this.
