### ISSUE TITLE
Ruby 2.3.0 suport

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-client#42]
Needs a release of celluloid-io, https://github.com/celluloid/celluloid-io/pull/163.

**Comment by harlantwood** [comment]
Looks like that's done -- https://rubygems.org/gems/celluloid-io/versions/0.17.3

Any other known issues with Ruby 2.3.0?

**Comment by dblock** [comment]
Closed via https://github.com/dblock/slack-ruby-client/pull/65.
