### ISSUE TITLE
Celluloid support is broken

### ISSUE THREAD

**Issue by jlyonsmith** [dblock/slack-ruby-client#46]
[celluloid.rb](https://github.com/dblock/slack-ruby-client/blob/master/lib/slack/real_time/concurrency/celluloid.rb#L12).  Should be using `::Celluloid::Internals::Logger` and not `::Celluloid::Logger` for current release version of Celluloid (0.17.2)

If you don't think this ought to be fixed, can you know a working combination of ruby-slack-client, Celluloid & Reel versions?

**Comment by dblock** [comment]
This doesn't seem to be a problem when running the integration test, `spec/integration/integration_spec.rb`, what am I missing?

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/slack-ruby-client/commit/33360aaf947204f6d4a213a2dbbba43f5c5af42d, based on #47 but with specs reproducing the issue.
