### ISSUE TITLE
Add Celluloid support next to EventMachine

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-client#5]
See https://github.com/abstractive/slack-ruby-gem/commit/41a45ba11a11c087b501654a159e72f27526dd9d.

**Comment by digitalextremist** [comment]
I'll add Celluloid support, as I have in the other gem. Two things though. I'd actually use `Reel::IO` ( celluloid/reel-io#2 ) and I'd also use [this http gem](https://github.com/httprb/http) instead.

**Comment by dblock** [comment]
@digitalextremist are you saying we should replace Faraday for httprb? I would be open to it, but I am not sure it matters for slack-ruby-client given that HTTP communication is hardly the overhead.

**Comment by digitalextremist** [comment]
Correct, it is unrelated to the `WebSocket` aspect, so I will post a second ticket for this piece. Why I mention it is that this `http` gem is compatible with `Celluloid::IO` which makes it evented, and in my uses, I do have many concurrent requests taking place at once in many cases.

**Comment by mikz** [comment]
I'm really interested in this. Is there a way I could help?

**Comment by dblock** [comment]
Please contribute @mikz!

**Comment by mikz** [comment]
I'd like not to clash on some ongoing work. I plan to make a prototype using just celluloid-io and websocket-driver without using reel-io.

**Comment by mikz** [comment]
@dblock @digitalextremist I did a prototype. See the code in https://github.com/dblock/slack-ruby-client/commit/ced303d099334a1a7dd191da827e3676487a6228. It successfully connected to slack and was answering with celluloid.

The celluloid integration is probably not very correct. It crashes on Ctrl-C. 

What I'd like to do next:

* cover it with tests that work for both concurrency options
* refactor the socket / client so it is more understandable

**Comment by dblock** [comment]
This is very good. I actually think this whole code should be a gem that abstracts various ways of doing concurrency.

**Comment by mikz** [comment]
@dblock opened #15 for discussion

tuned a bit the original prototype so now it detects what you have available
tried both realtime examples and they work

it is possible that some cases are broken, like closing connection or processing some messages
but rather to show it early than go the wrong path

**Comment by dblock** [comment]
Closing via https://github.com/dblock/slack-ruby-client/pull/26. Please try Celluloid support on HEAD.
