### ISSUE TITLE
Missing ENV[SLACK_API_TOKEN]! (RuntimeError)

### ISSUE THREAD

**Issue by kamal2222ahmed** [dblock/slack-ruby-client#64]
running the example @ slack-ruby-client/examples/hi_web/hi.rb

```
#!/opt/chefdk/embedded/bin/ruby

require 'slack-ruby-client'

Slack.configure do |config|
  config.token = ENV['the API Token...... provided by Slack Admin']
  fail 'Missing ENV[SLACK_API_TOKEN]!' unless config.token
end

client = Slack::Web::Client.new

client.auth_test

client.chat_postMessage(channel: '#gradle', text: 'Hello World', as_user: true)
```

fails with:

./hi.rb
./hi.rb:7:in `block in <main>': Missing ENV[SLACK_API_TOKEN]! (RuntimeError)
        from /home/skahmed/.chefdk/gem/ruby/2.1.0/gems/slack-ruby-client-0.6.0/lib/slack/config.rb:14:in `configure'
        from ./hi.rb:5:in `<main>'

/opt/chefdk/embedded/bin/ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

**Comment by dblock** [comment]
This is expected, to connect to Slack you need a Slack API token, so run it with

```
SLACK_API_TOKEN=... ruby slack-ruby-client/examples/hi_web/hi.rb
```

See https://github.com/dblock/slack-ruby-client#create-a-new-bot-integration for how to make a token.

**Comment by kamal2222ahmed** [comment]
i have the API Token , i just did not show it in the code pasted
ref: ENV['the API Token...... provided by Slack Admin']
so the question is how does the API knows where the base URL is for Slack, since we have a slacker server @ mycompany.slack.com

**Comment by dblock** [comment]
If your token is `xyz` and your code is  `config.token = ENV['the API Token...... provided by Slack Admin']`, aka `ENV['xyz']`, you are assigning the value in ENV with the key `xyz` to the token, but you want the token itself, so `config.token = "xyz"`.

You don't really have an isolated server with Slack, just a shortcut that lets you access your slack team, called "mycompany" in this case. Slack API is separate and it will use the token to figure out your team information and will connect your client to the right place.
