### ISSUE TITLE
Slack:Config.logger is not working

### ISSUE THREAD

**Issue by FreedomCoder** [dblock/slack-ruby-client#71]
Whenever creating a client or a bot the log levels are not respected. 

```ruby
Slack::Web::Client.config do |config|
    config.logger = Logger.new("test.log")
    config.logger.level = Logger::UNKNOWN
 end

  Slack::RealTime::Client.config do |config|
    config.logger = Logger.new("test.log")
    config.logger.level = Logger::UNKNOWN
 end

  Slack.configure do |config|
    config.logger = Logger.new("test.log")
    config.logger.level = Logger::UNKNOWN
  end
```

App will still log everything to STDOUT and do not respect any sort of logging.

**Comment by dblock** [comment]
I don't see any problem with this code, you can see how these are assigned in https://github.com/dblock/slack-ruby-client/blob/472d508557db8e19fdf3fc10e328e4bd48dbd327/lib/slack/web/client.rb#L14 and such. In theory you should just be able to configure the last one for both web and real time.

Are you saying `test.log` isn't even created? Maybe show a simple example with output you're seeing that you don't expect?

**Comment by FreedomCoder** [comment]
@dblock  sorry maybe I was not clear enough. I do set those parameters and then I still get STDOUT logs displaying such as:

```
D, [2016-03-13T22:16:56.643837 #92413] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#parse: HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: iXXXXXXXXXXXXXXXX=


D, [2016-03-13T22:16:56.645792 #92413] DEBUG -- SlackRubyBot::Client#run_loop: Faye::WebSocket::API::OpenEvent
D, [2016-03-13T22:16:56.708562 #92413] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#parse: ?{"type":"hello"}
D, [2016-03-13T22:16:56.709825 #92413] DEBUG -- SlackRubyBot::Client#run_loop: Faye::WebSocket::API::MessageEvent, {"type":"hello"}
D, [2016-03-13T22:16:56.709963 #92413] DEBUG -- SlackRubyBot::Client#dispatch: type=hello
I, [2016-03-13T22:16:56.710123 #92413]  INFO -- : Welcome proto to the XXXXXXXX team.
I, [2016-03-13T22:16:56.710188 #92413]  INFO -- : Successfully connected to https://XXXXX.slack.com.
D, [2016-03-13T22:16:56.710275 #92413] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#parse: ?~?{"type":"reconnect_url","url":"wss://mpmxxxxxx.slack-msgs.com/websocket/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="}

```

I am trying to get ride of such STDOUT logs since they are leaking sensitive data. As you can see it is writting down, debug, Info, warm, etc.. I saw your code and yes the simple Slack.configure should have fixed them all and reduce them to UNKNOWN or WARM, but sadly it did not. I might be doing something stupid wrong, but the reason behind this is that I am ok with this while testing, but I do not want to have all this info on the production version of the app.

**Comment by dblock** [comment]
You're using SlackRubyBot, that injects its own logger in, try this:

```ruby
Slack.configure do |config|
  # your logger
  config.logger = Logger.new(STDOUT)
  config.logger.level = Logger::WARN
end

SlackRubyBot::Client.logger.level = Logger::WARN
```

I can see how this is confusing. Maybe to start document this in slack-ruby-bot?

**Comment by FreedomCoder** [comment]
@dblock I knew it was me doing something dumb. Sorry and thanks for the help. I could not find any documentation in bot regarding logs so I figured it was all on client side of things. 

I was trying to do this:
```ruby
SlackRubyBot.configure do |config|
  config.logger = Logger.new(STDOUT)
  config.logger.level = Logger::WARN
end
```
and because it failed I moved to client. I will close the ticket since it solved my question. 

Cheers and great code :+1:

**Comment by dblock** [comment]
@FreedomCoder Would you do me a favor and PR something about this to slack-ruby-bot README? Thanks!
