### ISSUE TITLE
usergroups_list missing scope

### ISSUE THREAD

**Issue by zenmatt** [dblock/slack-ruby-client#77]
Hi, I'm getting a missing scope error from the Slack API when trying the usergroups_list method on a team that has usergroups:read scope authentication. Has anyone else run into this issue?

**Comment by dblock** [comment]
I would start [here](https://api.slack.com/docs/oauth-scopes). I'd like some documentation on this in slack-ruby-client so will leave this open.

**Comment by zenmatt** [comment]
To be more clear, I'm wondering if this is an issue with slack-ruby-client and if anyone else has successfully used this method with a properly authed team.


Error:
`client.usergroups_list(group: "@testgroup")
Slack::Web::Api::Error: missing_scope
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/faraday/response/raise_error.rb:9:in `on_complete'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/faraday/request.rb:25:in `request'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/faraday/request.rb:10:in `post'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/api/endpoints/usergroups.rb:68:in `usergroups_list'`


The scope for the authed team:
`               :scope => "identify,bot,usergroups:read",`

**Comment by dblock** [comment]
If I am reading https://api.slack.com/methods/usergroups.list correctly this method doesn't take `group`, but `include_disabled`, `include_users`, etc. No?

**Comment by zenmatt** [comment]
I'm sorry you are correct, I was thinking of the usergroups.users.list method in the Slack API (which is not implemented) and doing it from memory. I actually do run it with just `include_users` and still get a similar error:

```
client.usergroups_list(include_users: 1)
Slack::Web::Api::Error: missing_scope
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/faraday/response/raise_error.rb:9:in `on_complete'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/faraday/request.rb:25:in `request'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/faraday/request.rb:10:in `post'
	from /var/www/snippets-bot/shared/bundle/ruby/2.2.0/bundler/gems/slack-ruby-client-9a1245a6ada8/lib/slack/web/api/endpoints/usergroups.rb:68:in `usergroups_list'
```

**Comment by dblock** [comment]
How did you obtain a token before calling this?

**Comment by zenmatt** [comment]
Via oauth_access during installation, it's a production app and this is the only method we're having trouble with.

**Comment by dblock** [comment]
I am seeing the same thing. I think you should [ask slack](https://dblockdotorg.slack.com/help/requests/new), let us know here what you find.

**Comment by zenmatt** [comment]
Ok I've opened a ticket, will relay updates to the thread.

**Comment by zenmatt** [comment]
The issue appears to be that you need to use `access_token` with the client, not `bot_access_token` for this method. Confusing and easy to miss in the documentation.

**Comment by dblock** [comment]
You supply the client ID and secret for the app and the login code and get back the bot token to act on behalf of the bot. But I never knew it also returned a user piece.

You sure that that token doesn't represent the producer of the bot?

**Comment by zenmatt** [comment]
They call it a "top level access token" on this page: https://api.slack.com/docs/oauth. It says: "You can then use this token to call API methods on behalf of the user" vs `bot_access_token` which is on behalf of the bot. Super confusing IMO.

**Comment by dblock** [comment]
Thanks @zenmatt.
