### ISSUE TITLE
channels_invite is giving a missing scope error

### ISSUE THREAD

**Issue by JasonMannon** [dblock/slack-ruby-client#78]
Did something happen with this endpoint that it doesn't work anymore?

`client.channels_invite(channel: "slack_channel_id", user: "slack_user_id")`  

And in response I get this: 

`Slack::Web::Api::Error: missing_scope`

**Comment by dblock** [comment]
@JasonMannon you closed this? Care to elaborate for the next person?

**Comment by JasonMannon** [comment]
Yes, I closed it because I am using the Slack Button.  And I believe I was getting the missing scope error, because when using the Slack Button it doesn't allow me to invite users to channels/groups.  But, if you aren't using the Slack Button you should have no issues using `channels_invite`.

**Comment by dblock** [comment]
It's more about what scopes you ask for and what token you end up using. But yes.
