### ISSUE TITLE
`config.logger` throws undefined method error

### ISSUE THREAD

**Issue by FuzzWorley** [dblock/slack-ruby-client#79]
When i try to implement:
```ruby
Slack.configure do |config|
  config.token = ENV['SLACK_TOKEN']
  config.logger = Logger.new(STDOUT)
  config.logger.level = Logger::WARN
end
```
as copied verbatim from the `hi.rb` example in the documentation, I get an error: "Projects/rubot/config/initializers/assets.rb:15:in block in <top (required)>': undefined methodlogger=' for Slack::Config:Module (NoMethodError)".

The application works fine if I don't use`.logger`.

I'm using Rails 4.2.5.1. Please help. It's been a nightmare to debug with no logs.

**Comment by dblock** [comment]
Which version of slack-ruby-client are you using?

**Comment by dblock** [comment]
Note that https://github.com/dblock/slack-ruby-client/blob/9a1245a6ada876f2437a461b6a698edcb286cae4/examples/hi_real_time/hi.rb is a working sample.

**Comment by FuzzWorley** [comment]
I was running 0.6.0. Updated to 0.7.0 which fixed the issue. Whoops! Thanks for making such a great library!
