### ISSUE TITLE
image_url and thumb_url attachments not working

### ISSUE THREAD

**Issue by bbshih** [dblock/slack-ruby-client#83]
I got attachments working for everything but image_url and thumb_url. I tried debugging and couldn't find any reason why this doesn't work. Any ideas?

```
@client = Slack::Web::Client.new
@client.chat_postMessage(channel: '#promotions-updates', text: "image test", attachments: [
  {
    image_url: "http://placehold.it/350x150.gif"
  }
], as_user: true)
```

**Comment by dblock** [comment]
I've been using those in another project successfully and slack-ruby-client just passes things through. 

I noticed that sometimes Slack chooses not to render those images, but I have no idea why. I also wonder whether they support GIFs here. Either way I would write a very simple repro for this and ask Slack Help, unless you can demonstrate that it works with `curl` and doesn't work with this library.

**Comment by bbshih** [comment]
Your GIF suggestion led me to figuring it out. The problem is that it doesn't show the image if you are missing a title in the attachment.

You can close this out. Thanks!

**Comment by dblock** [comment]
Interesting! Is this documented?

I'll close the issue.

**Comment by bbshih** [comment]
I couldn’t find it in the documents. I’m going to open a issue in their github docs. Seems like it just needs text of some sort to display, so if it’s alone, it doesn’t display anything.
