### ISSUE TITLE
Celluloid concurrency doesn't parallelize the connection setup

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-client#84]
Celluloid creates an `Actor` which then performs a connection. Even if you put this inside a `Celluloid.defer` (as I did in https://github.com/dblock/slack-market/commit/3635cddd0f9f421e20211b9c10eb76cda4a079b8) it doesn't seem to happen in parallel, `build_socket` is blocking. This causes server start with lots of connections to be very slow, as we create TCP connections one-at-a-time.

**Comment by dblock** [comment]
@mikz Maybe you can help with this?

**Comment by dblock** [comment]
I also asked https://groups.google.com/forum/#!topic/celluloid-ruby/Xa8pdXP3h4A.

**Comment by mikz** [comment]
I have not worked with Celluloid enough to get this problem. 

The [connect](https://github.com/dblock/slack-ruby-client/blob/fcfe9b25d7a0e5bbc7fdea86c679e8f84d31194b/lib/slack/real_time/concurrency/celluloid.rb#L91-L94) is happening synchronously iirc.
That part could be wrapped in some actor, but then the status could not be immediate and would have to use Future.

**Comment by dblock** [comment]
@mikz I thought that using `Celluloid.defer` around this would do it, but I couldn't make it happen in parallel.

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/slack-ruby-client/commit/e4edaca9f9611d5ea006c34607d3a1f803d3a627.
