### ISSUE TITLE
Celluloid::IO support handles concurrency incorrectly

### ISSUE THREAD

**Issue by benzrf** [dblock/slack-ruby-client#92]
The advantage of `Celluloid::IO` is that it gives you the ability to make IO calls which suspend the current task but do not block the actor as a whole. The realtime client doesn't make proper use of this, though - after reading from the socket, it immediately handles the input synchronously within the same task, so the input loop will not proceed to the next iteration until the handler is done. The net result is that the program can only handle one incoming message at once.

**Comment by benzrf** [comment]
Here's an example:

```ruby
require 'celluloid/current'
require 'slack-ruby-bot'

class TestBot < SlackRubyBot::Bot
  command 'expensive' do |client, data, match|
    Celluloid::Actor.current.sleep 2
    client.say(text: 'Done with expensive', channel: data.channel)
  end

  command 'cheap' do |client, data, match|
    client.say(text: 'Done with cheap', channel: data.channel)
  end
end

TestBot.run
```

https://gfycat.com/LikableLavishAtlanticridleyturtle

**Comment by dblock** [comment]
Thanks. You're right, would really appreciate a PR that fixes this. There're other celluloid-io questions like #84 and #90.

**Comment by benzrf** [comment]
I did manage to make a small change that gets my example bot working, but I'm not really sure what repercussions the change would have, or if other parts might need changing. I'll attach it.

**Comment by benzrf** [comment]
See #93.

**Comment by benzrf** [comment]
Thanks for the merge :)
