### ISSUE TITLE
Bot User is always inactive

### ISSUE THREAD

**Issue by polysaturate** [dblock/slack-ruby-client#94]
I couldn't find any open/closed issues or any reason in the source code for my following issue. 

When setting up a user like so:

`client = Slack::Web::Client.new({token: @token_var})`

and then sending a message to a channel or user:

`client.chat_postMessage(channel:  client.users_info(user: '@rob').user.id, text: 'Hello World', as_user: true)`

...works, but always shows the bot as 'away', even using the client API to set the presence.

**Comment by dblock** [comment]
Sending a message doesn't make a bot. The code above is a web client. If you want the bot to be active you need a real-time connection. You might want to watch http://code.dblock.org/2016/03/11/your-first-slack-bot-service-video.html.
