### ISSUE TITLE
Module conflicts with slack-api gem

### ISSUE THREAD

**Issue by m5rk** [dblock/slack-ruby-client#95]
I am adding this gem to a project that also uses the slack-api gem. Perhaps I only need one?

Since they both use the top-level `Slack` module, they do not peacefully coexist.

**Comment by dblock** [comment]
This gem was a replacement and a superset of https://github.com/aki017/slack-ruby-gem, which is `slack-api`. It more clearly separates the Web and RTM APIs, is more thoroughly tested and is in active development, so you definitely want to get rid of the other one.

**Comment by m5rk** [comment]
Thanks for following up. I removed slack-api.
