### ISSUE TITLE
chat.rb is missing chat.meMessage

### ISSUE THREAD

**Issue by aaronpk** [dblock/slack-ruby-client#97]
The Slack API supports a method `chat.meMessage` which sends a message like `/me waves`. https://api.slack.com/methods/chat.meMessage

I can't find this method in the `chat.rb` file https://github.com/dblock/slack-ruby-client/blob/master/lib/slack/web/api/endpoints/chat.rb

**Comment by dblock** [comment]
Closed via https://github.com/dblock/slack-ruby-client/commit/546cc9d79c6ad3261e69ca065e80193d1e58ea76.

**Comment by dblock** [comment]
I've released 0.7.5 with these api updates, FYI.
